#!/bin/bash
#SBATCH --job-name=maxwell_filter
#SBATCH --ntasks-per-node=1
#SBATCH --mem=12G
#SBATCH --time=02:00:00

# PBS is a computer software that performs job-scheduling
# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana U
#
# This is the main file run by the brainlife.io orchestration system
#
# Author: Franco Pestilli


set -e
set -x

# Make output directories
mkdir -p out_dir
mkdir -p out_dir_report

# Run the actual python code
singularity exec docker://brainlife/mne:0.23dev python3 maxwell_filter.py
