#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=02:00:00
#PBS -N maxfilter

# PBS is a computer software that performs job-scheduling
# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana U
#
# This is the main file run by the brainlife.io orchestration system
#
# Author: Franco Pestilli


set -e
set -x

# make output directory
mkdir -p out_dir

# run the actual python code
singularity exec docker://brainlife/dipy:1.1.1 python3 maxfilter.py
